package com.kartaguez.pocoma.domain.pot.authorization;

public enum PotAction {
	VIEW_POT,
	UPDATE_POT_DETAILS,
	DELETE_POT,
	VIEW_SHAREHOLDER,
	ADD_SHAREHOLDER,
	UPDATE_SHAREHOLDER_DETAILS,
	UPDATE_SHAREHOLDER_WEIGHTS,
	REMOVE_SHAREHOLDER,
	VIEW_EXPENSE,
	CREATE_EXPENSE,
	UPDATE_EXPENSE_DETAILS,
	UPDATE_EXPENSE_SHARES,
	DELETE_EXPENSE,
	VIEW_BALANCE
}
