spring.application.name=pocoma
spring.flyway.enabled=false
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.probes.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.pocoma.projection.end_to_end.latency=true
