spring.application.name=pocoma-balance-calculation-tasks-dispatcher
spring.main.web-application-type=none
spring.flyway.enabled=false
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.probes.enabled=true
management.prometheus.metrics.export.enabled=true
pocoma.projection.worker.enabled=true
pocoma.projection.worker.mode=polling
pocoma.projection.worker.task-builder-enabled=false
pocoma.projection.worker.task-executor-enabled=true
pocoma.projection.worker.event-listener-enabled=false
pocoma.projection.nats.enabled=true
pocoma.projection.nats.servers=${POCOMA_NATS_SERVERS:nats://localhost:4222}
pocoma.projection.nats.projection-tasks-available-subject=${POCOMA_NATS_PROJECTION_TASKS_AVAILABLE_SUBJECT:pocoma.projection.tasks.available}
pocoma.projection.nats.projection-tasks-processed-subject=${POCOMA_NATS_PROJECTION_TASKS_PROCESSED_SUBJECT:pocoma.projection.tasks.processed}
