package com.kartaguez.pocoma.supra.worker.task;

public enum TaskWorkerRunOutcome {
	IDLE,
	EXECUTED_AND_COMPLETED,
	ALREADY_EXECUTED_AND_COMPLETED,
	TASK_EXECUTION_FAILED,
	RELEASED_BEFORE_EXECUTION,
	OWNERSHIP_LOST,
	TECHNICAL_ERROR,
	LEASE_WARNING,
	LEASE_EXCEEDED
}
