spring.datasource.url=${POCOMA_POSTGRES_URL:jdbc:postgresql://localhost:5432/pocoma}
spring.datasource.username=${POCOMA_POSTGRES_USER:pocoma}
spring.datasource.password=${POCOMA_POSTGRES_PASSWORD:pocoma}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
