package com.kartaguez.pocoma.supra.worker.event;

public enum EventWorkerRunOutcome {
	IDLE,
	TASKS_CREATED_AND_COMPLETED,
	TASKS_ALREADY_CREATED_AND_COMPLETED,
	ZERO_TASKS_CREATED_AND_COMPLETED,
	TASK_CREATION_FAILED,
	RELEASED_BEFORE_CREATION,
	OWNERSHIP_LOST,
	TECHNICAL_ERROR,
	LEASE_WARNING,
	LEASE_EXCEEDED
}
