spring.application.name=pocoma-worker
spring.main.web-application-type=none
spring.flyway.enabled=false
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.probes.enabled=true
management.prometheus.metrics.export.enabled=true
pocoma.projection.worker.enabled=true
pocoma.projection.worker.task-builder-enabled=true
pocoma.projection.worker.task-executor-enabled=true
